$file = "F:\CodingMan\Code2Git\03-Project_00\02-nex\02.01-nexCM\02.01.02-nexCM-V3\src\views\system\config\index.vue"
$lines = Get-Content $file -Encoding UTF8
$newLines = @()

$startLine = 607
$endLine = 691

$correctContent = @(
'              <el-form-item>',
'                <template slot="label">',
'                  <span class="config-label-tip">',
'                    {{ $t(''menu.system.config.childrenMenu.device.partLifeReminderEnabled'') }}',
'                    <el-tooltip :content="$t(''menu.system.config.childrenMenu.device.partLifeReminderEnabledTip'')" placement="top">',
'                      <i class="el-icon-question tip-icon"></i>',
'                    </el-tooltip>',
'                  </span>',
'                </template>',
'                <el-switch',
'                  v-model="form.partLifeReminderEnabled"',
'                  :active-value="true"',
'                  :inactive-value="false"',
'                />',
'              </el-form-item>',
'',
'              <el-form-item>',
'                <template slot="label">',
'                  <span class="config-label-tip">',
'                    {{ $t(''menu.system.config.childrenMenu.device.partLifeThreshold'') }}',
'                    <el-tooltip :content="$t(''menu.system.config.childrenMenu.device.partLifeThresholdTip'')" placement="top">',
'                      <i class="el-icon-question tip-icon"></i>',
'                    </el-tooltip>',
'                  </span>',
'                </template>',
'                <el-select',
'                  v-model="form.partLifeThreshold"',
'                  style="width: 200px"',
'                  :disabled="!form.partLifeReminderEnabled"',
'                >',
'                  <el-option label="10%" value="10" />',
'                  <el-option label="20%" value="20" />',
'                  <el-option label="30%" value="30" />',
'                  <el-option label="50%" value="50" />',
'                </el-select>',
'              </el-form-item>',
'',
'              <el-form-item>',
'                <template slot="label">',
'                  <span class="config-label-tip">',
'                    {{ $t(''menu.system.config.childrenMenu.device.partLifeRemindInterval'') }}',
'                    <el-tooltip :content="$t(''menu.system.config.childrenMenu.device.partLifeRemindIntervalTip'')" placement="top">',
'                      <i class="el-icon-question tip-icon"></i>',
'                    </el-tooltip>',
'                  </span>',
'                </template>',
'                <el-select',
'                  v-model="form.partLifeRemindInterval"',
'                  style="width: 200px"',
'                  :disabled="!form.partLifeReminderEnabled"',
'                >',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.intervalHour'')',
'                    "',
'                    value="hour"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.intervalShift'')',
'                    "',
'                    value="shift"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.intervalDay'')',
'                    "',
'                    value="day"',
'                  />',
'                </el-select>',
'              </el-form-item>',
'',
'              <el-form-item>',
'                <template slot="label">',
'                  <span class="config-label-tip">',
'                    {{ $t(''menu.system.config.childrenMenu.device.snoozeInterval'') }}',
'                    <el-tooltip :content="$t(''menu.system.config.childrenMenu.device.snoozeIntervalTip'')" placement="top">',
'                      <i class="el-icon-question tip-icon"></i>',
'                    </el-tooltip>',
'                  </span>',
'                </template>',
'                <el-select',
'                  v-model="form.partLifeSnoozeInterval"',
'                  style="width: 200px"',
'                  :disabled="!form.partLifeReminderEnabled"',
'                >',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.snooze5min'')',
'                    "',
'                    value="5"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.snooze10min'')',
'                    "',
'                    value="10"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.snooze30min'')',
'                    "',
'                    value="30"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.snooze1hour'')',
'                    "',
'                    value="60"',
'                  />',
'                  <el-option',
'                    :label="',
'                      $t(''menu.system.config.childrenMenu.device.snooze2hour'')',
'                    "',
'                    value="120"',
'                  />',
'                </el-select>',
'              </el-form-item>'
)

for ($i = 0; $i -lt $startLine - 1; $i++) {
  $newLines += $lines[$i]
}
$newLines += $correctContent
for ($i = $endLine; $i -lt $lines.Count; $i++) {
  $newLines += $lines[$i]
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($file, $newLines, $utf8NoBom)

Write-Host "Done! Replaced lines $startLine-$endLine with $($correctContent.Count) lines"
