/**
 * Production Module - Order Management Internationalization Fields (English)
 * Note: No fallback solution, missing fields directly display the key
 */
export default {
  // [Action] Add
  add: 'Add',
  // [Action] Delete
  delete: 'Delete',
  // [Action] Download
  download: 'Download',
  // [Action] Edit
  edit: 'Edit',
  // [Menu] Order management (default menu title)
  default: 'Order Management',

  // ===== Order board view (migration additions) =====
  export: 'Export',
  reportBtn: 'Generate report',
  reportTodo: 'Order PDF report pending report-tool integration',
  empty: 'No orders',
  tabRunning: 'Running',
  tabCompleted: 'Completed',
  tabPlanned: 'Planned',
  colOrderNo: 'Order No.',
  colProduct: 'Product',
  colBottleType: 'Bottle type',
  colProgress: 'Progress',
  colQty: 'Done/Total',
  colPriority: 'Priority',
  colStartDate: 'Start date',
  colRecipe: 'Recipe',
  colOperator: 'Operator',
  priority: {
    high: 'High',
    medium: 'Medium',
    low: 'Low'
  },
  stat: {
    total: 'Total orders',
    completed: 'Completed',
    running: 'Running',
    planned: 'Planned'
  },
  // [Submodule] Page
  page: {
    // [Label] Alarm count
    alarmCount: 'Alarm Count',
    // [Label] Batch no
    batchNo: 'Batch No.',
    // [Placeholder] Batch no placeholder
    batchNoPlaceholder: 'Enter batch number',
    // [Status] Completed
    completed: 'Completed',
    // [Label] Completed qty
    completedQty: 'Completed Qty',
    // [Label] End time
    endTime: 'End Time',
    // [Label] Estimated end
    estimatedEnd: 'Estimated End',
    // [Placeholder] Estimated end placeholder
    estimatedEndPlaceholder: 'Select estimated end time',
    // [Label] No order production
    noOrderProduction: 'No Order Production',
    // [Label] Operator
    operator: 'Operator',
    // [Label] Order no
    orderNo: 'Order No.',
    // [Placeholder] Order no placeholder
    orderNoPlaceholder: 'Enter order number',
    // [Status] Planned
    planned: 'Planned',
    // [Tip] Planned no download
    plannedNoDownload: 'Cannot download in planned status',
    // [Label] Product name
    productName: 'Product Name',
    // [Placeholder] Product name placeholder
    productNamePlaceholder: 'Enter product name',
    // [Label] Qualified rate
    qualifiedRate: 'Qualified Rate',
    // [Label] Recipe name
    recipeName: 'Recipe Name',
    // [Placeholder] Recipe name placeholder
    recipeNamePlaceholder: 'Enter recipe name',
    // [Status] Running
    running: 'Running',
    // [Tip] Running no download
    runningNoDownload: 'Cannot download in running status',
    // [Label] Runtime
    runtime: 'Runtime',
    // [Tip] Select order tip
    selectOrderTip: 'Please select an order',
    // [Label] Start time
    startTime: 'Start Time',
    // [Placeholder] Start time placeholder
    startTimePlaceholder: 'Select start time',
    // [Label] Status
    status: 'Status',
    // [Status] Status completed
    statusCompleted: 'Completed',
    // [Status] Status planned
    statusPlanned: 'Planned',
    // [Status] Status running
    statusRunning: 'Running',
    // [Label] Target qty
    targetQty: 'Target Qty',
    // [Label] Download count
    downloadCount: 'Download Count',
    // [Label] Qualified qty
    qualifiedQty: 'Qualified Qty',
    // [Label] Unqualified qty
    unqualifiedQty: 'Unqualified Qty',
    // [Submodule] Tips
    tips: {
      // [Tip] Batch no
      batchNo: 'Unique number of the production batch',
      // [Tip] Estimated end
      estimatedEnd: 'Estimated production completion time',
      // [Tip] Order no
      orderNo: 'Unique number of the order',
      // [Tip] Product name
      productName: 'Name of the product being produced',
      // [Tip] Recipe name
      recipeName: 'Name of the recipe being used',
      // [Tip] Start time
      startTime: 'Time when production started',
      // [Tip] Target qty
      targetQty: 'Planned production quantity'
    }
  },
  // [Submodule] Order production report
  report: {
    // [Label] Report title
    title: 'Order Production Report',
    // [Label] Report generated by
    generatedBy: 'Generated By',
    // [Label] Report generated at
    generatedAt: 'Generated At',
    // [Label] Basic information
    basicInfo: 'Basic Information',
    // [Label] Production statistics
    productionStats: 'Production Statistics',
    // [Label] Alarm detail
    alarmDetail: 'Alarm Detail',
    // [Label] Operator detail
    operatorDetail: 'Operator Detail'
  }
}
